version: '3'
services:
  api:
    image: api
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - api-node-modules:/api/node_modules
      - ./backend:/api
    environment:
      PORT: 8082
    ports:
      - 8082:8082
volumes:
  api-node-modules:
