version: '2'
services:
  web:
    image: web
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - web-node-modules:/web/node_modules
      - ./frontend:/web
    depends_on:
      - web_reverse_connection
    ports:
      - "80:80"
    networks:
      - web
  web_reverse_connection:
    image: ngrok/ngrok
    container_name: web_reverse_connection
    environment:
      NGROK_AUTHTOKEN: '5W1bR67GNbWcXqmxZzBG1_56GezNeaX6sSRvn8npeQ8'
    command: 'http --subdomain=swimmer-reaction-timer-meter-web web:80'
    restart: unless-stopped
    networks:
      - web
  api_reverse_connection:
    image: ngrok/ngrok
    container_name: api_reverse_connection
    environment:
      NGROK_AUTHTOKEN: '5W1bR67GNbWcXqmxZzBG1_56GezNeaX6sSRvn8npeQ8'
    command: 'http --subdomain=swimmer-reaction-timer-meter-api api:8082'
    restart: unless-stopped
    networks:
      - api
  api:
    image: api
    depends_on: 
      - api_reverse_connection
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - api-node-modules:/api/node_modules
      - ./backend:/api
    environment:
      PORT: 8082
    restart: unless-stopped
    ports:
      - "8082:8082"
    networks:
      - api
volumes:
  api-node-modules:
  web-node-modules:

networks:
  api:
  web:
